cuda_visible_devices: 2

data_path: data/ml-1m/
project_path: negative_feedback/

dataset:
  user_col: user_id
  item_col: item_id
  relevance_col: rating
  relevance_threshold: 4
  max_length: 100

dataloader:
  batch_size: 500
  test_batch_size: 500
  num_workers: 16
  validation_size: 10000

trainer_params:
  max_epochs: 100

patience: 10

model:
  dropout: 0.10
  hidden_units: 231
  lr: 0.001
  num_blocks: 2
  neg_CE_coef: 0.45
  contrastive_coef: 0.25
