cuda_visible_devices: 0

ml_flow:
  set_tracking_uri: file:/home/jovyan/mlruns
  set_experiment: sasrec_baselines_ml1m

data_path: data/ml-1m/

dataset:
  user_col: user_id
  item_col: item_id
  relevance_col: rating
  relevance_threshold: 4
  max_length: 100

dataloader:
  batch_size: 500
  test_batch_size: 500
  num_workers: 16
  validation_size: 10000

trainer_params:
  max_epochs: 100

patience: 10
